### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Azareeltv** [kockeNN/esx-kocken-postnord#1]
Error parsing script @esx-postnord/server/main.lua in resource esx-postnord: @esx-postnord/server/main.lua:13: ')' expected (to close '(' at line 12) near 'end'
Failed to load script server/main.lua.

**Comment by Terranzin** [comment]
In server/main.lua change row 12 to following

> TriggerClientEvent("esx:showNotification", _source, ('Du klarade av körningen och tog emot ~g~'..moneytoget..' SEK'))

**Comment by lord0o** [comment]
fixed in #2
